######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 10 14:09:25 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
